name: Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint  mypy

    - name: Lint with pylint
      run: |
        # stop the build if pylint is 10 for everything
        pylint .

    - name: Lint with mypy
      run: |
        # stop the build if pylint is 10 for everything
        mypy .
    

