name: Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: bclipp770/aws_lambda_builder:latest
    steps:
      - uses: actions/checkout@v2
      # Normally, we would use the superbly maintained...
      # - uses: actions/setup-python@v2
      #   with:
      #    python-version: ${{ matrix.python-version }}
      # ... but in the repo, we want to test pyenv builds on Ubuntu
      # https://github.com/pyenv/pyenv#installation
      - run: pwd
      - env:
          PYENV_ROOT: /home/runner/work/pyenv/pyenv
        run: |
          yum install -y which zip
          echo $PYENV_ROOT
          echo "$PYENV_ROOT/shims:$PYENV_ROOT/bin" >> $GITHUB_PATH
          export PATH="/root/.pyenv/bin:$PATH" 
          eval "$(pyenv init -)" 
          eval "$(pyenv virtualenv-init -)"
          which pyenv
          whoami
          pyenv install 3.9.2
          pyenv global 3.9.2
          pyenv rehash
          pyenv virtualenv 3.9.2 awsLambdaEnv
          pyenv activate awsLambdaEnv
          pip install pylint mypy
          pylint .
          # mypy .
          mkdir lambda_deployment
          cp -r __init__.py lambda_function.py  lambda_deployment
          cd lambda_deployment
          pip3 install -t ./package  pandas
          cd package
          zip -r9 ../../lambda_function.zip .
          cd ..
          rm -rf package/
          zip -gr ../lambda_function.zip *
          
