name: Python

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: bclipp770/aws_lambda_builder:latest
    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - env:
          PYENV_ROOT: /home/runner/work/pyenv/pyenv
      run: |
          echo $PYENV_ROOT
          echo "$PYENV_ROOT/shims:$PYENV_ROOT/bin" >> $GITHUB_PATH
          bin/pyenv install ${{ matrix.python-version }}
          bin/pyenv global ${{ matrix.python-version }}
          bin/pyenv rehash
    - run: python --version

    - name: Install dependencies
      run: |
        pip3 install pylint  mypy

    - name: Lint with pylint
      run: |
        pylint .

    - name: Lint with mypy
      run: |
        # stop the build if pylint is 10 for everything
        mypy .

    - name: Build Zip & deploy Zip
      run: |
        mkdir lambda_deployment
        cp -r __init__.py lambda_function.py  lambda_deployment
        cd lambda_deployment
        pip3 install -t ./package -r pandas
        cd package
        zip -r9 ../../lambda_function.zip .
        cd ..
        rm -rf package/
        zip -gr ../lambda_function.zip *

    

